name = "galpi-payment-worker"
main = "src/index.ts"
compatibility_date = "2024-02-23"

[vars]
# PAYMINT_BASE_URL = "http://stg.paymint.co.kr:10200"
# PAYMINT_API_KEY = "..."
# PAYMINT_MEMBER = "..."
# PAYMINT_MERCHANT = "..."
# GOOGLE_FORM_URL = "..."
# WORKER_URL = "https://galpi-payment-worker.wisgraph.workers.dev"

[[kv_namespaces]]
binding = "PAYMENTS_KV"
id = "..." # Cloudflare 대시보드에서 생성 후 ID 입력 필요
